### ISSUE TITLE
some animation in overlay foots is floating 

### ISSUE THREAD

**Issue by asumadelta** [Sixze/ALS-Refactored#402]
I found problem with foots is floating I think is small problem but when I add new mesh to use with ALS it float a lot.

animation that make foots floating 
-binocular
-bow
-default
-M4
-pistol one hand
-pistol two hand

https://github.com/Sixze/ALS-Refactored/assets/23005914/36b8c497-babe-4bb1-a0da-1a3d6c03d5f7

**Comment by Sixze** [comment]
There is a limit to how far the leg can stretch, previously it was set to 99% of the leg length, but I have increased it to 99.9%, I believe this should be enough.

You can adjust it yourself if you want, the limit is located in `CR_Als`, in the `ClampFootIkLocationByLegLength` function, but I recommend not to go beyond 100%, otherwise problems with leg IK may occur, for example the knee may start bending in the wrong direction.
