### ISSUE TITLE
Collision issue on Linux and Android.

### ISSUE THREAD

**Issue by Alex-G** [Sixze/ALS-Refactored#63]
On Linux and Android sometimes you got stuck and you can't move anymore.
If you try to move the camera flies inside you, and you stay in the same position.
It happens randomly, but I noticed that it happens often if the Ai runs into you.

**Comment by Alex-G** [comment]
https://user-images.githubusercontent.com/5215249/157503165-1ef70899-0304-43b5-b94b-492491f228bb.mp4
Bug demonstration on Android

**Comment by Alex-G** [comment]
https://user-images.githubusercontent.com/5215249/157908397-54d538f4-0ac6-4b51-a419-5b29ebab1d75.mp4

For some reason the Mesh of the character starts to scale to a gigantic size when you start to move, after colliding the something.

**Comment by Sixze** [comment]
Are there any logs? Maybe they can help figure out what's going on.

**Comment by Alex-G** [comment]
In the hope to get some useful logs, I tried to run a debug build.
in the debug build this bug with the big character does not appear, so maybe this bug occurs because the (clang Android/Linux) optimizes something away? 🤔

**Comment by Sixze** [comment]
It seems that this issue is related to the incorrect scaling of the bones when applying additive animations. The position of the camera depends on the position of the bones, which is why it shifts so much inside the character.

The issue from the last video seems to be a physics issue, the character should not be able to walk on this step.

Can you please try to somehow get the logs and test the сommunity version of the plugin in the same conditions? Did the plugin version for Unreal Engine 4.26 or 4.27 also have these issues?

**Comment by Alex-G** [comment]
the incorrect scaling of the bones happens on all Engine versions < 5.
On UE 5.0 this does not happen.
the physics issue happens UE5 no matter C++ / BP on Andoid.

**Comment by Sixze** [comment]
Does this mean that the bone scaling issue is no longer relevant? 😄

As for the physics problem, I suggest to wait until the full release of Unreal Engine 5.0. You can also download the 3rd person template that comes with the engine and test this bug with the character blueprint from there, try to walk on a step of the same height as in the video.
